version: '3.7'
services:
  db:
    container_name: db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: Wy63B9Xcoy6uE6R
      MYSQL_DATABASE: ShiftODB
      MYSQL_USER: shifto_app
      MYSQL_PASSWORD: "Wy63B9Xcoy6uE6R"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - './data/db:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: shifto_app
      PMA_PASSWORD: "Wy63B9Xcoy6uE6R"
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  # backend:
  #   image: faiazhalim/shifto-backend:latest
  #   container_name: backend
  #   links:
  #     - db
  #   restart: always
  #   ports:
  #     - 8080:8080